#!/usr/bin/env python

import os
import json

from config import configer
from crawler.query.query import Query
from crawler.query.builder import Builder
from crawler.crawler import Crawler
from db.driver import Driver

MEMBERS_PATH = os.path.join(os.path.dirname(__file__), './raw/members.json')
MEMBERS_FILE = os.path.abspath(MEMBERS_PATH)


def main():
    config = configer.config('teamwork')
    query_config = configer.config('bigquery')

    #crawler = Crawler(config['organization'].lower())
    #crawler.add_members()

    query = Query(query_config)
    builder = Builder(config['organization'].lower())

    driver = Driver(config)
    driver.connect()

    result = query.execute(builder.build())

    if (result == [] or result is None):
        pass
    else:
        driver.insert('raw', result)

    with open(MEMBERS_FILE, 'r') as f:
        members = json.loads(f.read())
        f.close()

    driver.filter_rows(members)
    driver.disconnect()

if __name__ == '__main__':
    main()
