#!/usr/bin/env python

import os
import json
from datetime import date, timedelta

from config import configer
from db.driver import Driver
from scanner import contributions

MEMBERS_PATH = os.path.join(os.path.dirname(__file__), './raw/members.json')
MEMBERS_FILE = os.path.abspath(MEMBERS_PATH)


def main():
    config = configer.config('teamwork')

    driver = Driver(config)
    driver.connect()

    field = 'repository_pushed_at'
    time_series = driver.raw_ref.with_fields(field).order_by(field).run()

    start = date.today() - timedelta(days=365)
    org_data = contributions.contributions(time_series, start, 'organization')

    driver.create_table('contributions')
    driver.insert('contributions', org_data) 

    driver.disconnect()

if __name__ == '__main__':
    main()
